### ISSUE TITLE
Question: License agreement

### ISSUE THREAD

**Issue by Lukemtesta** [AllenHunn/LoggingWrapper#2]
Hey Allen,

This is a great project which provides an almost out-of-the-box solution for a unified managed/native logger - Something that seems quite rare when looking around (unless someone authors their own wrapper). 

I'd love to use the project but I cannot find a license agreement. 

What kind of license is attached to this project? Is it okay to use this with my windows app? Can I deploy the dll with a reference to your project? 

Let me know your thoughts!

Regards,
Luke

**Comment by AllenHunn** [comment]
Sorry for the late reply, I don't check this often. I added a MIT license, so feel free to use it however you'd like.
